# Generated by Django 3.2.5 on 2022-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_alter_drug_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='count',
            field=models.IntegerField(verbose_name='количество на складе'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='фото лекарства'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название лекарства'),
        ),
    ]
