# Generated by Django 3.2.5 on 2022-05-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='militaryID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='speciality',
        ),
    ]
