# Generated by Django 3.2.5 on 2022-05-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220513_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Qualification',
        ),
    ]
