# Generated by Django 3.2.5 on 2022-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='iin',
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=models.CharField(default=1, max_length=12, verbose_name='Часы/Кабинет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Type_of_education',
            field=models.CharField(choices=[('Высшее', 'Высшее'), ('Среднее-специальное', 'Среднее-специальное'), ('среднее', 'Среднее')], max_length=100),
        ),
    ]
