# Generated by Django 3.2.5 on 2022-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220526_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cabinet',
            field=models.CharField(default=11, max_length=15, verbose_name='Кабинет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='schedule',
            field=models.CharField(max_length=100, verbose_name='Часы приема'),
        ),
    ]
